// <auto-generated />
using System;
using ErongoIT.Backup.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ErongoIT.Backup.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BackupDbContext))]
    [Migration("20260827054653_AddDeviceAssignedBackupPlan")]
    partial class AddDeviceAssignedBackupPlan
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ErongoIT.Backup.Domain.Entities.BackupContent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("Sha256")
                        .IsUnique();

                    b.ToTable("backup_content", (string)null);
                });

            modelBuilder.Entity("ErongoIT.Backup.Domain.Entities.BackupFile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BackupContentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BackupJobId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("BackupContentId");

                    b.HasIndex("BackupJobId");

                    b.HasIndex("BackupJobId", "RelativePath")
                        .IsUnique();

                    b.ToTable("backup_files", (string)null);
                });

            modelBuilder.Entity("ErongoIT.Backup.Domain.Entities.BackupJob", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BackupPlanId")
                        .HasColumnType("uuid");

                    b.Property<long>("BytesSelected")
                        .HasColumnType("bigint");

                    b.Property<long>("BytesUploaded")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BackupPlanId", "StartedAtUtc");

                    b.HasIndex("CustomerId", "StartedAtUtc");

                    b.HasIndex("DeviceId", "StartedAtUtc");

                    b.HasIndex("Status", "StartedAtUtc");

                    b.ToTable("backup_jobs", (string)null);
                });

            modelBuilder.Entity("ErongoIT.Backup.Domain.Entities.BackupPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<int>("IntervalMinutes")
                        .HasColumnType("integer");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("RetentionDays")
                        .HasColumnType("integer");

                    b.Property<int>("ScheduleDayOfWeek")
                        .HasColumnType("integer");

                    b.Property<int>("ScheduleTimeMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("ScheduleType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("CustomerId", "IsEnabled");

                    b.HasIndex("CustomerId", "Name")
                        .IsUnique();

                    b.ToTable("backup_plans", null, t =>
                        {
                            t.HasCheckConstraint("CK_backup_plans_interval_minutes_min", "\"IntervalMinutes\" >= 15");

                            t.HasCheckConstraint("CK_backup_plans_retention_days_positive", "\"RetentionDays\" > 0");

                            t.HasCheckConstraint("CK_backup_plans_schedule_day_valid", "\"ScheduleDayOfWeek\" >= 0 AND \"ScheduleDayOfWeek\" <= 6");

                            t.HasCheckConstraint("CK_backup_plans_schedule_time_valid", "\"ScheduleTimeMinutes\" >= 0 AND \"ScheduleTimeMinutes\" <= 1439");

                            t.HasCheckConstraint("CK_backup_plans_schedule_type_valid", "\"ScheduleType\" IN (1, 2, 3)");
                        });
                });

            modelBuilder.Entity("ErongoIT.Backup.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ContactEmail");

                    b.HasIndex("Name");

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("ErongoIT.Backup.Domain.Entities.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AgentVersion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("AssignedBackupPlanId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Hostname")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastSeenAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("OperatingSystem")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedBackupPlanId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("LastSeenAtUtc");

                    b.HasIndex("CustomerId", "Name")
                        .IsUnique();

                    b.ToTable("devices", (string)null);
                });

            modelBuilder.Entity("ErongoIT.Backup.Domain.Entities.BackupFile", b =>
                {
                    b.HasOne("ErongoIT.Backup.Domain.Entities.BackupContent", null)
                        .WithMany()
                        .HasForeignKey("BackupContentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ErongoIT.Backup.Domain.Entities.BackupJob", null)
                        .WithMany()
                        .HasForeignKey("BackupJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ErongoIT.Backup.Domain.Entities.BackupJob", b =>
                {
                    b.HasOne("ErongoIT.Backup.Domain.Entities.BackupPlan", null)
                        .WithMany()
                        .HasForeignKey("BackupPlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ErongoIT.Backup.Domain.Entities.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ErongoIT.Backup.Domain.Entities.Device", null)
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ErongoIT.Backup.Domain.Entities.BackupPlan", b =>
                {
                    b.HasOne("ErongoIT.Backup.Domain.Entities.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ErongoIT.Backup.Domain.Entities.Device", b =>
                {
                    b.HasOne("ErongoIT.Backup.Domain.Entities.BackupPlan", null)
                        .WithMany()
                        .HasForeignKey("AssignedBackupPlanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ErongoIT.Backup.Domain.Entities.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
